--NOTE: NOT FOR USE, SIMPLY FOR REFERENCE--
--ALL SQL IN POSTGRESQL--
CREATE DATABASE SysScribe
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    users VARCHAR(250),
    password VARCHAR(250)
);
CREATE TABLE issues (
    id SERIAL PRIMARY KEY,
    userID INT NOT NULL,
    issueName VARCHAR(255) NOT NULL,
    issueStatus VARCHAT(255) DEFAULT 'Reported',
    description TEXT,
    creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    FOREIGN KEY (userID) REFERENCES users(id) ON DELETE CASCADE
);